Repository nestauk/nesta, pull requests merged in 2019-08, with the labels that each got.

#125 Deepchange analysis
  nesta/packages/arxiv/deepchange_analysis.py
  nesta/packages/arxiv/tests/test_deepchange_analysis.py
  nesta/packages/mag/query_mag_api.py
  nesta/packages/mag/tests/test_query_mag.py
  nesta/production/database_scripts/arxlive_deepchange.sql
  nesta/production/database_scripts/fetch_geography_codes.sparql
  nesta/production/database_scripts/uk_geography_name.sparql
  nesta/production/routines/arxiv/arxiv_collect_iterative_task.py
  nesta/production/routines/arxiv/arxiv_iterative_root_task.py
  nesta/production/routines/arxiv/deepchange_analysis_task.py
  requirements.txt
Labels: enhancement

#144 Updated luigi example routines
  nesta/packages/examples/example_package.py
  nesta/packages/examples/tests/test_example_package.py
  nesta/production/batchables/examples/template_batchable/run.py
  nesta/production/orms/example_orm.py
  nesta/production/routines/examples/batch_example/batch_example.py
  nesta/production/routines/examples/simple_example/example_simple_pipeline.py
  nesta/production/routines/examples/template_pipeline_no_batch.py
  nesta/production/routines/examples/template_pipeline_with_batch.py
  nesta/production/routines/examples/template_pipeline_with_batch_2.py
Labels: bug, enhancement

#145 Put the LIVE in arXlive.
  docker/Dockerfile
  docker/README.rst
  docker/docker-compose-arxlive-dev.yml
  docker/luigi_logging_docker.cfg
  docker/run.sh
  nesta/packages/arxiv/collect_arxiv.py
  nesta/packages/arxiv/tests/test_collect_arxiv.py
  nesta/packages/mag/query_mag_sparql.py
  nesta/production/orms/arxiv_orm.py
  nesta/production/routines/arxiv/arxiv_collect_iterative_task.py
  nesta/production/routines/arxiv/arxiv_es_task.py
  nesta/production/routines/arxiv/arxiv_grid_task.py
  nesta/production/routines/arxiv/arxiv_mag_sparql_task.py
  nesta/production/routines/arxiv/arxiv_mag_task.py
  nesta/production/routines/arxiv/arxiv_root_task.py
  nesta/production/routines/arxiv/arxiv_topic_tasks.py
  nesta/production/scripts/arxlive.sh
  requirements.txt
Labels: enhancement

#112 Adding NiH mesh terms, remapping CB analyzer,
  nesta/packages/geo_utils/geocode.py
  nesta/packages/health_data/process_mesh.py
  nesta/packages/nlp_utils/preprocess.py
  nesta/packages/nomis/nomis.py
  nesta/packages/wikipedia/wiktionary_ngrams.py
  nesta/packages/worldbank/collect_worldbank.py
  nesta/production/batchables/health_data/nih_abstract_mesh_data/run.py
  nesta/production/batchables/health_data/nih_dedupe/run.py
  nesta/production/batchables/health_data/nih_dedupe/tests/test_nih_dedupe.py
  nesta/production/batchables/health_data/nih_process_data/run.py
  nesta/production/batchables/meetup/topic_tag_elasticsearch/run.py
  nesta/production/luigihacks/elasticsearchplus.py
  nesta/production/luigihacks/estask.py
  nesta/production/luigihacks/tests/test_elasticsearchplus.py
  nesta/production/orms/crunchbase_es_config.json
  nesta/production/orms/nih_es_config.json
  nesta/production/orms/orm_utils.py
  nesta/production/orms/tests/test_orm_utils.py
  nesta/production/routines/arxiv/topic_process_task_chain.json
  nesta/production/routines/clio/clio_process_task_chain.json
  nesta/production/routines/health_data/nih_data/_nih_process_task.py
  nesta/production/routines/health_data/nih_data/nih_abstracts_mesh_task.py
  nesta/production/routines/health_data/nih_data/nih_dedupe_task.py
  nesta/production/routines/health_data/nih_data/nih_process_task.py
  nesta/production/routines/health_data/nih_data/nih_root_task.py
  nesta/production/schemas/tier_1/aliases/health_scanner.json
  nesta/production/scripts/docker_recipes/py36_amzn1_image/launch.sh
  nesta/production/scripts/nesta_prepare_batch
Labels: enhancement

#162 Upgrade setuptools.
  requirements.txt
Labels: bug

#160 Add topic modelling automatically to GtR task chain
  nesta/core/batchables/arxiv/arxiv_elasticsearch/arxiv.json
  nesta/core/batchables/nlp/corex_topic_model/run.py
  nesta/core/batchables/nlp/ngrammer/run.py
  nesta/core/batchables/nlp/synonyms/run.py
  nesta/core/batchables/nlp/vectorizer/run.py
  nesta/core/luigihacks/automl.py
  nesta/core/luigihacks/luigi_logging.py
  nesta/core/luigihacks/s3.py
  nesta/core/luigihacks/s3task.py
  nesta/core/routines/clio/clio_process_task_chain.json
  nesta/core/routines/clio/clio_task.py
Labels: enhancement

#163 Increase luigi workers for arXlive.
  docker/README.rst
  nesta/core/routines/arxiv/deepchange_analysis_task.py
  nesta/core/scripts/arxlive.sh
Labels: bug

#166 94a novl mesh
  nesta/core/batchables/meetup/topic_tag_elasticsearch/run.py
  nesta/core/luigihacks/s3task.py
  nesta/core/orms/crunchbase_es_config.json
  nesta/core/orms/meetup_es_config.json
  nesta/core/routines/clio/clio_process_task_chain.json
  nesta/core/routines/clio/clio_task.py
  nesta/core/routines/crunchbase/crunchbase_lolvelty.py
  nesta/core/routines/crunchbase/crunchbase_root_task.py
  nesta/core/routines/meetup/health_tagging/health_meetup_es_task.py
  nesta/core/routines/meetup/health_tagging/meetup_lolvelty.py
  nesta/core/schemas/tier_1/aliases/health_scanner.json
  nesta/core/schemas/tier_1/schema_transformations/meetup.json
Labels: enhancement
