Repository nestauk/nesta, pull requests merged in 2019-05, with the labels that each got.

#68 Arxiv iterative
  nesta/packages/arxiv/collect_arxiv.py
  nesta/packages/arxiv/tests/test_collect_arxiv.py
  nesta/packages/geo_utils/geocode.py
  nesta/packages/mag/query_mag.py
  nesta/packages/mag/tests/test_query_mag.py
  nesta/packages/misc_utils/batches.py
  nesta/packages/misc_utils/tests/test_batches.py
  nesta/production/batchables/arxiv/arxiv_collect/run.py
  nesta/production/orms/arxiv_orm.py
  nesta/production/orms/mag_orm.py
  nesta/production/orms/orm_utils.py
  nesta/production/orms/tests/test_orm_utils.py
  nesta/production/routines/arxiv/arxiv_collect_all_task.py
  nesta/production/routines/arxiv/arxiv_collect_iterative_task.py
  nesta/production/routines/arxiv/arxiv_iterative_date_task.py
  nesta/production/routines/arxiv/arxiv_iterative_root_task.py
  nesta/production/routines/arxiv/arxiv_mag_task.py
  nesta/production/routines/arxiv/arxiv_root_task.py
  requirements.txt
Labels: enhancement

#75 Mag sparql
  nesta/packages/arxiv/collect_arxiv.py
  nesta/packages/arxiv/tests/test_collect_arxiv.py
  nesta/packages/geographies/uk_geography_lookup.py
  nesta/packages/mag/query_mag_api.py
  nesta/packages/mag/query_mag_sparql.py
  nesta/packages/mag/tests/test_query_mag.py
  nesta/packages/misc_utils/batches.py
  nesta/packages/misc_utils/sparql_query.py
  nesta/production/routines/arxiv/arxiv_collect_iterative_task.py
  nesta/production/routines/arxiv/arxiv_iterative_root_task.py
  nesta/production/routines/arxiv/arxiv_mag_sparql_task.py
  nesta/production/routines/arxiv/arxiv_mag_task.py
  requirements.txt
Labels: enhancement

#85 Crunchbase mesh labelling
  nesta/packages/health_data/process_mesh.py
  nesta/production/orms/crunchbase_orm.py
  nesta/production/routines/crunchbase/crunchbase_elasticsearch_task.py
  nesta/production/routines/crunchbase/crunchbase_mesh_task.py
  nesta/production/routines/crunchbase/crunchbase_root_task.py
  nesta/production/schemas/tier_1/schema_transformations/crunchbase_organisation_members.json
  nesta/production/schemas/tier_1/tier_1.json
Labels: enhancement

#82 Data cleaning (health and GtR)
  make_requirements.sh
  nesta/packages/crunchbase/crunchbase_collect.py
  nesta/packages/crunchbase/tests/test_crunchbase_collect.py
  nesta/packages/decorators/schema_transform.py
  nesta/packages/format_utils/datetools.py
  nesta/packages/gtr/get_gtr_data.py
  nesta/packages/gtr/tests/test_gtr.py
  nesta/packages/health_data/process_nih.py
  nesta/production/batchables/crunchbase/crunchbase_collect/run.py
  nesta/production/batchables/crunchbase/crunchbase_elasticsearch/run.py
  nesta/production/batchables/gtr/run.py
  nesta/production/batchables/health_data/nih_abstract_mesh_data/run.py
  nesta/production/batchables/health_data/nih_process_data/run.py
  nesta/production/luigihacks/elasticsearchplus.py
  nesta/production/luigihacks/misctools.py
  nesta/production/luigihacks/tests/test_elasticsearchplus.py
  nesta/production/orms/crunchbase_es_config.json
  nesta/production/orms/crunchbase_orm.py
  nesta/production/orms/gtr_orm.py
  nesta/production/orms/nih_es_config.json
  nesta/production/orms/orm_utils.py
  nesta/production/orms/tests/test_crunchbase.py
  nesta/production/orms/tests/test_orm_utils.py
  nesta/production/routines/clio/clio_task.py
  nesta/production/routines/crunchbase/crunchbase_elasticsearch_task.py
  nesta/production/routines/crunchbase/crunchbase_org_collect_task.py
  nesta/production/routines/crunchbase/crunchbase_root_task.py
  nesta/production/routines/gtr/gtr_collect.py
  nesta/production/routines/health_data/nih_data/nih_abstracts_mesh_task.py
  nesta/production/routines/health_data/nih_data/nih_collect_task.py
  nesta/production/routines/health_data/nih_data/nih_process_task.py
  nesta/production/routines/health_data/nih_data/nih_root_task.py
  nesta/production/schemas/tier_1/aliases/health_scanner.json
  nesta/production/schemas/tier_1/field_null_mappings/health_scanner.json
  nesta/production/schemas/tier_1/schema_transformations/crunchbase_organisation_members.json
  nesta/production/schemas/tier_1/schema_transformations/nih.json
  nesta/production/schemas/tier_1/tests/test_validate.py
  nesta/production/schemas/tier_1/tier_1.json
  nesta/production/scripts/docker_recipes/py36_amzn1_image/Dockerfile
  nesta/production/scripts/nesta_prepare_batch
  requirements.txt
Labels: bug, enhancement

#83 Grid
  .travis.yml
  nesta/packages/arxiv/collect_arxiv.py
  nesta/packages/arxiv/tests/test_collect_arxiv.py
  nesta/packages/grid/grid.py
  nesta/packages/grid/tests/test_grid.py
  nesta/packages/mag/query_mag_sparql.py
  nesta/packages/mag/tests/test_query_mag.py
  nesta/production/orms/arxiv_orm.py
  nesta/production/orms/grid_orm.py
  nesta/production/routines/arxiv/arxiv_grid_task.py
  nesta/production/routines/arxiv/arxiv_iterative_root_task.py
  nesta/production/routines/arxiv/arxiv_mag_sparql_task.py
  requirements.txt
Labels: enhancement

#88 Requirements upgrade
  make_requirements.sh
  nesta/packages/geo_utils/country_iso_code.py
  requirements.txt
Labels: bug
