Repository nestauk/nesta, pull requests merged in 2020-05, with the labels that each got.

#223 Cordis to elasticsearch [prototype for EURITO]
  nesta/core/batchables/cordis/cordis_api/run.py
  nesta/core/batchables/eurito/cordis_eu/run.py
  nesta/core/batchables/eurito/cordis_eu/test_cordis2es.py
  nesta/core/orms/arxiv-eu_es_config.json
  nesta/core/orms/cordis-eu_es_config.json
  nesta/core/routines/eurito_es/es_root.py
  nesta/core/schemas/tier_1/schema_transformations/eurito/arxiv-eu.json
  nesta/core/schemas/tier_1/schema_transformations/eurito/cordis-eu.json
  nesta/core/schemas/tier_1/tier_1.json
  nesta/packages/cordis/cordis_api.py
  nesta/packages/geo_utils/lookup.py
  sort_all_json.py
Labels: dataset:CORDIS, proj: EURITO, service: AWS, tech: ES

#233 Upgrade sentencepiece version
  requirements.txt
Labels: dependencies

#226 [224] arxlive lolvelty fix
  nesta/core/routines/arxiv/arxiv_root_task.py
Labels: proj:ai in research

#237 Add inf exception and reduced server load
  nesta/core/routines/gtr/gtr_collect.py
  nesta/core/routines/gtr/gtr_geocode.py
  nesta/packages/gtr/get_gtr_data.py
Labels: dataset:gtr

#235 [228a] bior/medr/xiv tier-0 collection
  nesta/core/luigihacks/sql2estask.py
  nesta/core/orms/arxiv_orm.py
  nesta/core/routines/arxiv/arxiv_collect_iterative_task.py
  nesta/core/routines/arxiv/arxiv_grid_task.py
  nesta/core/routines/arxiv/arxiv_lolvelty.py
  nesta/core/routines/arxiv/arxiv_mag_sparql_task.py
  nesta/core/routines/arxiv/arxiv_mag_task.py
  nesta/core/routines/arxiv/arxiv_topic_tasks.py
  nesta/core/routines/arxiv/magrxiv_collect_iterative_task.py
  nesta/core/routines/arxiv/tests/test_magrxiv.py
  nesta/packages/mag/parse_abstract.py
  nesta/packages/magrxiv/collect_magrxiv.py
  nesta/packages/magrxiv/test_collect_biorxiv.py
Labels: dataset:biorxiv

#248 [247] Fix dodgy filter syntax
  nesta/core/routines/arxiv/arxiv_topic_tasks.py
Labels: bug, proj: arxlive

#251 [250] VARCHAR length wasn't in pkey check
  nesta/core/orms/orm_utils.py
  nesta/core/orms/tests/test_orm_utils.py
Labels: bug

#245 [244] Joblib corex fix
  nesta/core/routines/arxiv/arxiv_topic_tasks.py
  nesta/core/scripts/docker_recipes/py36_sklearn_amzn1_image/Dockerfile
  nesta/core/scripts/docker_recipes/py36_sklearn_amzn1_image/launch.sh
Labels: bug

#239 [238] Automate GtR data collection
  docker/docker-compose-gtr-dev.yml
  nesta/core/routines/gtr/gtr_collect.py
  nesta/core/routines/gtr/test_gtr_pipeline.py
  nesta/core/scripts/gtr.sh
Labels: dataset:gtr

#256 [255] force send email from luigi/cron/docker tasks
  nesta/core/scripts/arxlive.sh
  nesta/core/scripts/gtr.sh
Labels: broken pipeline, bug

#258 [257] Add date tagger
  dev_tag.sh
Labels: enhancement

#260 [252] Switch on patstat
  nesta/core/routines/eurito_es/es_root.py
Labels: dataset:patstat, proj: EURITO

#261 [244] Reinstated corex after PR merged into corex master
  nesta/core/scripts/docker_recipes/py36_sklearn_amzn1_image/launch.sh
Labels: dataset:arxiv, proj: arxlive

#263 added hook to forbid commits to dev and master
  .githooks/pre-commit
Labels: enhancement
